### ISSUE TITLE
CET6_edited.txt 与 CET4_edited.txt

### ISSUE THREAD

**Issue by qbit-git** [mahavivo/wordlists#5]
请问 CET6_edited.txt 与 CET4_edited.txt 什么关系？
为什么 CET6_edited.txt 比 CET4_edited.txt 单词个数少，并且很多重复？

**Comment by mahavivo** [comment]
cet4和cet6之间可能有重复词汇是因为词表的来源不同。不同的整理者有不同的思路、观念与认知，并非一定要严格符合什么教育部的大纲之类，比如说，某个词汇并不在所谓的六级大纲词汇表里，但出现在了某年的六级考试当中，你认为它是六级词汇吗？我只是这些来源歧异的网络文档的汇集整理者，方便自己使用，发现有明显的讹误，顺手改一下，并没有从头严密规划、分类、整理了这些词汇，我又不是教育部门的官员或者托福、GRE考试的官方，词表大体适用即可，并不需要对之严格做出划定区分。

**Comment by qbit-git** [comment]
> cet4和cet6之间可能有重复词汇是因为词表的来源不同。不同的整理者有不同的思路、观念与认知，并非一定要严格符合什么教育部的大纲之类，比如说，某个词汇并不在所谓的六级大纲词汇表里，但出现在了某年的六级考试当中，你认为它是六级词汇吗？我只是这些来源歧异的网络文档的汇集整理者，方便自己使用，发现有明显的讹误，顺手改一下，并没有从头严密规划、分类、整理了这些词汇，我又不是教育部门的官员或者托福、GRE考试的官方，词表大体适用即可，并不需要对之严格做出划定区分。

好的，谢谢。
